### ISSUE TITLE
Problem with ogg

### ISSUE THREAD

**Issue by janaab11** [Vernacular-ai/st-record#1]
Tried running the dev server in Chrome. throws an ogg incompatible error. Dunno if this is a Chrome issue or i built things incorrectly. I followed the documentation from [here](https://docs.streamlit.io/en/stable/develop_streamlit_components.html#development-environment-setup)

**Comment by lepisma** [comment]
Ok looks like ogg is a bad idea. I wanted to record raw wave. In any case I think webm is more supported. Will see.

Also packaging will be fixed in next version.
